*WIP* Add  target="_blank" to footer links
manyfold3d/manyfold pull request #2200
Opened 2024-05-23 20:03 UTC by chryton

Adding an affordance to open non-internal links in a new tab to avoid confusion and help users posting issues without having to destroy the current UI state

## Checklist

- [X] Make sure you are making a pull request against our **main branch** (left side)
- [X] Check that that your branch is up to date with our main.
- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request *your* main!
- [ ] Check that the tests and code linter both pass.
- [x] If you're a new contributor, please sign our [contributor license agreement](https://cla-assistant.io/manyfold3d/manyfold).

## Warnings

None

## Summary

- Adds `target="_blank"` to footer urls pointing to external domains

## Linked issues

None

## Description of changes

- Makes the links in the footer open new tabs/windows for all external domains
- If you are concerned with security, [modern browsers now default](https://chromestatus.com/feature/6140064063029248) to `rel="noopener"` to avoid rogue JS taking over the requesting site

2024-05-23 21:51 UTC, Floppy approved these changes

2024-05-23 22:04 UTC, chryton commented
Looks like docker build (token issue) and rubylint (dep issue) issues are existing issues in `main`. Let me know if you need anything from me to get these passing!

2024-05-23 22:26 UTC, Floppy commented
The Docker build I expect to fail, something to do with forks, but the linter issue is real: `Rails/LinkToBlank: Specify a `:rel` option containing noopener.` on In file: app/views/application/_footer.html.erb line 13

2024-05-23 22:27 UTC, Floppy commented
Looks like it wants explicit `rel=noopener` despite that being now default behaviour.

2024-05-23 22:30 UTC, chryton commented
🙃 It also helps if I read the _full_ linting error... I'll fix shortly

2024-05-28 10:40 UTC, Floppy requested changes
added noopener rel to fix lint errors

2024-05-28 10:40 UTC, Floppy commented on app/views/application/_footer.html.erb
> +                "https://github.com/manyfold3d/manyfold/tree/#{ENV.fetch("GIT_SHA", "main")}", target: "_blank" %>
```suggestion
                "https://github.com/manyfold3d/manyfold/tree/#{ENV.fetch("GIT_SHA", "main")}", target: "_blank", rel: "noopener" %>
```

2024-05-28 10:44 UTC, Floppy approved these changes

2024-05-28 10:45 UTC, merged

2024-05-28 10:53 UTC, richyrb00 commented
@chryton don't forget rel="noopener noreferrer" on links that open new tab for security

2024-05-28 16:56 UTC, Floppy commented
I added the one the linter was complaining about already :+1: